@startuml
title ScooterHireApp - Class Diagram

class Person {
String name
  
}
class User {
scanQRCODE()
}
class MaintenancePersonnel {
String locateScooter
repairScooter()
}
class DockingStation {
chargeScooter()
lockScooter()
unlockScooter()
}


class Scooter {
+String location
+Integer scooterNumber
+Integer %Charge
+Boolean repairState
+Integer speedometer
rideScooter()
charge()

}

class ScooterHireApp{
-String accountDetails
+hireScooter()
+distanceTravelled
-getBillingAmount()
}

class ScooterHireAPI{
-validateDetails()
-validateCharge()
-validateRepairState

}

class ScooterHireDatabase{
-userDetails
+scooterDetails

}

Person <|-- User
Person <|-- MaintenancePersonnel

User "1" -- "1" Scooter : Hires
MaintenancePersonnel --> Scooter: Repairs
ScooterHireApp <-- User : UserData
Scooter --> ScooterHireApp:ScooterState
ScooterHireApp --> ScooterHireAPI
ScooterHireAPI <--> ScooterHireDatabase: Validates
User <-- ScooterHireApp : ScooterData
MaintenancePersonnel <-- ScooterHireAPI: BrokenScooterInfo
DockingStation <-- ScooterHireAPI:Once Validated, lock/unlock
Scooter --> DockingStation: Connects


@enduml